### ISSUE TITLE
More private way to store package credentials

### ISSUE THREAD

**Issue by davidferlay** [launchrctl/compose#1]
### Steps

- Create a compose.yaml file including a package repo with credentials
```
name: plasma
version: 1.0.0
dependencies:
- package: plasma-core
  source:
    type: git
    url: https://XXX.XXX.XXX/XXX/XXX.git
    auth:
      name: XXX
      password: XXX
```
- ./launchr compose

### Current

- compose.lock is created with clear credentials
```
hash: a0c1bf6ff2760b12dd268c8a6e82e305399550db057fae5029b0a9b006aced51
packages:
    - name: ""
      source:
        type: git
        url: https://XXX.XXX.XXX/XXX/XXX.git
        auth:
            name: XXX
            password: XXX
```
- compose.yaml also contains clear credentials

### Expected

- Would be great to looks for a way to avoid storing package/repos credentials in compose files
- Proposal: 
   - if package is not yet in compose.lock, user is prompted to enter package credentials when executing `./launchr compose `
   - credentials are only stored encrypted to compose.lock  and not stored in package.yaml at all

### Todo

- Implement proposed solution & feel free to challenge it
