### ISSUE TITLE
Name of package in compose.lock does not take name of package from compose.yaml

### ISSUE THREAD

**Issue by davidferlay** [launchrctl/compose#2]
### Steps

- Create a compose.yaml file including a package named `plasma-core`
```
name: plasma
version: 1.0.0
dependencies:
- package: plasma-core
  source:
    type: git
    url: https://XXX.XXX.XXX/XXX/XXX.git
```
- ./launchr compose

### Current

- compose.lock is created without package name `plasma-core`
```
hash: a0c1bf6ff2760b12dd268c8a6e82e305399550db057fae5029b0a9b006aced51
packages:
    - name: ""
      source:
        type: git
        url: https://XXX.XXX.XXX/XXX/XXX.git
```

### Expected

- Name of package in compose.lock should take name of package from compose.yaml
