### ISSUE TITLE
Using branch name as "ref" in compose.yaml throws an error

### ISSUE THREAD

**Issue by davidferlay** [launchrctl/compose#3]
### Steps

- Create a compose.yaml file including a package repo
```
name: plasma
version: 1.0.0
dependencies:
- package: plasma-core
  source:
    type: git
    ref: master
    url: https://XXX.XXX.XXX/XXX/XXX.git
```

### Current

- `./launchr compose` throws error:
```
Error: couldn't find remote ref "refs/tags/master"
```

- Interesting enough, removing `ref: master` from compose.yaml allows to fetch package from git master branch but that trick won't work for other branches

### Expected

- It should be possible to specify branch name as ref to fetch git package from

### Todo

- Implement branch ref support
