### ISSUE TITLE
Specify array of paths in strategies

### ISSUE THREAD

**Issue by davidferlay** [launchrctl/compose#33]
### Current

- User cannot define a strategy to affect several file
```
      strategy:
        - name: ignore-extra-package-files
          path:
            - library/inventories/platform_nodes/configuration/dev.yaml
```
Otherwise results in:
```
Error: incorrect mapping for compose.yaml, ensure structure is correct
```

### Expected

- Would be great to add ability to specify multiple paths per strategy: 
```
name: myproject
version: 1.0.0
dependencies:
  - package: compose-example
    source:
      type: git
      ref: 0.0.7
      url: https://github.com/iignatevich/compose-example.git
      strategy:
        - name: ignore-extra-package-files
          path:
            - library/inventories/platform_nodes/configuration/dev.yaml
            - library/inventories/platform_nodes/configuration/prod.yaml
            - library/inventories/platform_nodes/configuration/whatever.yaml
```
