### ISSUE TITLE
Ability to specify merge strategy for packages

### ISSUE THREAD

**Issue by davidferlay** [launchrctl/compose#4]
### Current

- There is no way to specify merge strategy of packages

### Expected

- Would be great to add ability to specify package strategy: 
	- to handle case when the same file differs bewteen local vs package: 
		- overwrite local file
		- overwrite package file
	- to handle case when some files exist in local but not in package, or the opposite: 
		- strict copy of package (and remove extra local files)
		- mix of both local and package files as long as no conflict
		- partial copy of package (and ignore extra package files)
- It could give ability to specify a different strategy per directory and file from package
- It could be an additional section of compose.yaml file like : 
```
name: myproject
version: 1.0.0
dependencies:
  - package: compose-example
    source:
      type: git
      ref: 0.0.7
      url: https://github.com/iignatevich/compose-example.git
    strategy:
      - some-dir/path/: remove-extra-local-files
      - some-other-dir/path/: ignore-extra-package-files
      - some-other-dir-again/path/: mix-local-and-package-files
      - some-file/dir/example.go: overwrite-local-file
      - some-file/dir/other-example.go: overwrite-package-file

```

**Comment by iignatevich** [comment]
https://github.com/launchrctl/compose/pull/14

**Comment by davidferlay** [comment]
Merged for https://github.com/launchrctl/compose/commit/745982491155a184146b8e53e015d3e6f8322614

Keep issue open to test further

**Comment by davidferlay** [comment]
As we start to have real cases, it appears it would be useful to have an additional strategy like so :+1: 
```
      strategy:
        - name: filter-package-files
          path: interaction/filtered-package-file.txt < Only this file will be taken from package (if it does not exists in domain?)
          path: interaction/filtered-package-folder < Only this directory will be taken from package (if it does not exists in domain)
```
In essence, it's the same as `ignore-extra-package-files` but works the opposite: instead of listing files to exclude from package, we list only files we take from package. That makes it more reliable because list does not need to be updated when new files are added to package
