### ISSUE TITLE
Can't compose with public repositories

### ISSUE THREAD

**Issue by davidferlay** [launchrctl/compose#42]
### Steps

```
➜  compose git:(citty) make all
➜  compose git:(citty) rm -rf .launchr/                                                            
➜  compose git:(citty) cat plasma-compose.yaml
name: launchr
dependencies:
  - name: example
    source:
      type: git
      ref: main
      url: https://github.com/launchrctl/launchr.git
      strategy: null
```

### Observed

- Composing with a public repo prompts user for credentials
```
➜  compose git:(citty) ./bin/launchr compose --skip-not-versioned --conflicts-verbosity --clean                           
Cleaning build dir: .compose/build
Cleaning packages dir: /home/dferlay/Sources/compose/.compose/packages
Please add login and password for URL - https://github.com/launchrctl/launchr.git
Username: 
```
- Adding empty credentials to keyring is not possible
```
➜  compose git:(citty) ./bin/launchr login --url=https://github.com/launchrctl/launchr.git --username="" --password="" --keyring-passphrase="***"
Error: item can't be empty
```

### Expected

- Composing with a public repo should not prompt user for credentials
