### ISSUE TITLE
Composition momentarily hanging

### ISSUE THREAD

**Issue by davidferlay** [launchrctl/compose#59]
### Steps

- Create a compose.yaml file including a package named `plasma-core`
```
name: plasma
version: 1.0.0
dependencies:
- package: plasma-core
  source:
    type: git
    url: https://XXX.XXX.XXX/XXX/XXX.git
```
- ./launchr compose

### Current

- Composition may hang quite a long time at this point
- From what I see, it's working but there is a long time where nothing is happening when processing pla-plasma repo. Maybe it's because of git repo size
- Or maybe it's before starting to clone any repo at all. 

Would be great to pin point exactly where time goes and what we can do about it. Even adding simple throbber could help

![image](https://github.com/user-attachments/assets/74cc4199-93b0-4534-a174-065560fe15b9)

### Expected

- Composition should not hang
