### ISSUE TITLE
Strategies bleeding to extra dirs/files

### ISSUE THREAD

**Issue by davidferlay** [launchrctl/compose#60]
### Current

- Let's consider a `plasma-compose` file like
```
name: plasma
dependencies:
 - name: plasma-core
    source:
      type: git
      tag: 1.92.0
      url: https://projects.skilld.cloud/skilld/pla-plasma.git
      strategy:
        - name: ignore-extra-package-files
          path:
            - interaction/services/roles/dashboards_grafana
```
- Excluding `interaction/services/roles/dashboards_grafana` also excludes other directories like `interaction/services/roles/dashboards_grafana_somethinge_else`

### Expected

- Excluding `interaction/services/roles/dashboards_grafana` should not bleed to other directories
